name: Rust

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Install latest nextest release
        uses: taiki-e/install-action@nextest
      - name: Build with no features
        run: cargo build --release --no-default-features --verbose
      - name: Build with all features
        run: cargo build --release --all-targets --all-features --verbose
      - name: Run tests with no default features
        run: cargo nextest run --release --no-default-features --run-ignored all --verbose
      - name: Run tests with all features
        run: cargo nextest run --release --all-targets --run-ignored all --verbose
